# Generated by Django 2.2 on 2022-02-08 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0130_holidays_except_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignschedule',
            name='except_type',
            field=models.CharField(blank=True, choices=[('1', 'NoSelect'), ('2', 'Inbound'), ('3', 'Outbound')], default='', max_length=10, null=True),
        ),
        # migrations.AlterField(
        #     model_name='uservariable',
        #     name='domain',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_switch', to='callcenter.Switch'),
        # ),
    ]
