# Generated by Django 2.2 on 2023-02-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0135_auto_20230221_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialtrunk',
            name='dial_digits',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
