# Generated by Django 2.2 on 2024-01-16 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0136_dialtrunk_dial_digits'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidays',
            name='is_global_holiday',
            field=models.BooleanField(blank=True, default=False, null=True),
        )

        
    ]
